### PR TITLE
can someone give me the contents of TeamColor

### PR DESCRIPTION
**Pull request by khang06**
Splatoon 2? I have USA, DM me.

### CODE REVIEW

**Comment by SunTheCourier** [comment]
Thanks Fam

**Comment by 466gaming** [comment]
Splatoon 2? I have USA, DM me.

**Comment by xDrixxyz** [comment]
Splatoon 2? I have USA, DM me.

**Comment by SunTheCourier** [comment]
God Damnit

**Comment by tumGER** [comment]
Splatoon 2? I have USA, DM me.

**Comment by ThatNerdyPikachu** [comment]
Splatoon 2? I have USA, DM me.

**Pull request merged**
